In [1]:
import pandas as pd

In [2]:
peru_field1 = pd.read_csv('original_data/Field_Sheets/BDF_2019_1.csv')
peru_field1.head()

,Codigo foto,Carpeta/Subcarpeta,Camara usada,Fecha,Familia,Genero,Especie,C贸digo/ ID del individuo*,Descripcion o Ubicacion,Quebrada-transecto,Colectores,Metodo de captura
0,DSC_0001-CV1-TRAMPA,Peces Morona Nov-2018/PECES CV1 Y CV2,Nikon 5300,11/23/2018,Erythrinidae,Hoplias,malabaricus,CV1-298,CV1-Mashumbara,Mashumbara,"Leo, Morgan, Antonio y Perciles",Red de espera
1,DSC_0001-CV2-TRAMPA,Peces Morona Nov-2018/PECES CV1 Y CV2,Nikon 5300,11/24/2018,Erythrinidae,Hoplias,malabaricus,CV2-491,CV2-Katirnaentsa,Katirnaentsa,"Leo, Morgan, Antonio y Perciles",Red de espera
2,DSC_0001-KANT1,Peces Morona Nov-2018/PECES CV1 Y CV2,Nikon 5300,11/24/2018,Erythrinidae,Erythrinus,erythrinus,CV2-299,CV2-Katirnaentsa,Kantashentsa-T1,"Leo, Morgan, Antonio y Perciles",Red de arrastre
3,DSC_0002-CV2-TRAMPA,Peces Morona Nov-2018/PECES CV1 Y CV2,Nikon 5300,11/24/2018,Anostomidae,Leporinus,friderici,CV2-492,CV2-Katirnaentsa,Katirnaentsa,"Leo, Morgan, Antonio y Perciles",Red de espera
4,DSC_0002-KANT1,Peces Morona Nov-2018/PECES CV1 Y CV2,Nikon 5300,11/24/2018,Cichlidae,Laetacara,flavilabris,CV2-300,CV2-Katirnaentsa,Kantashentsa-T1,"Leo, Morgan, Antonio y Perciles",Red de arrastre

In [10]:
peru_field1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 501 entries, 0 to 500
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Codigo foto                501 non-null    object
 1   Carpeta/Subcarpeta         501 non-null    object
 2   Camara usada               501 non-null    object
 3   Fecha                      501 non-null    object
 4   Familia                    501 non-null    object
 5   Genero                     501 non-null    object
 6   Especie                    501 non-null    object
 7   C贸digo/ ID del individuo*  501 non-null    object
 8   Descripcion o Ubicacion    501 non-null    object
 9   Quebrada-transecto         501 non-null    object
 10  Colectores                 501 non-null    object
 11  Metodo de captura          501 non-null    object
dtypes: object(12)
memory usage: 47.1+ KB

In [8]:
expanded_rows = []
for index, row in peru_field1.iterrows():
    row_dict = row.to_dict()
    codigo = row_dict['Codigo foto']
    if ' DSC' in codigo:
        codigo_split = codigo.split(' ')
        row_dict['file_name'] = codigo_split[0]
        expanded_rows.append(row_dict)
        row_dict['file_name'] = codigo_split[1]
        expanded_rows.append(row_dict)
    elif '-DSC' in codigo:
        codigo_split = codigo.split('-DSC')
        row_dict['file_name'] = codigo_split[0]
        expanded_rows.append(row_dict)
        row_dict['file_name'] = f'DSC{codigo_split[1]}'
        expanded_rows.append(row_dict)
    else:
        row_dict['file_name'] = codigo
        expanded_rows.append(row_dict)
expanded_df = pd.DataFrame(expanded_rows)

In [9]:
expanded_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 530 entries, 0 to 529
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Codigo foto                530 non-null    object
 1   Carpeta/Subcarpeta         530 non-null    object
 2   Camara usada               530 non-null    object
 3   Fecha                      530 non-null    object
 4   Familia                    530 non-null    object
 5   Genero                     530 non-null    object
 6   Especie                    530 non-null    object
 7   C贸digo/ ID del individuo*  530 non-null    object
 8   Descripcion o Ubicacion    530 non-null    object
 9   Quebrada-transecto         530 non-null    object
 10  Colectores                 530 non-null    object
 11  Metodo de captura          530 non-null    object
 12  file_name                  530 non-null    object
dtypes: object(13)
memory usage: 54.0+ KB

In [11]:
expanded_df.to_csv('cleaned_data/BDF_2019_1_expanded.tsv',
                   sep='\t', index=False)